package com.android.activelife.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CLASS_DATA".
 */
@Entity
public class ClassData {

    @Id(autoincrement = true)
    private Long id;
    private String class_id;
    private String class_name;
    private String class_description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ClassData() {
    }

    public ClassData(Long id) {
        this.id = id;
    }

    @Generated
    public ClassData(Long id, String class_id, String class_name, String class_description) {
        this.id = id;
        this.class_id = class_id;
        this.class_name = class_name;
        this.class_description = class_description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClass_id() {
        return class_id;
    }

    public void setClass_id(String class_id) {
        this.class_id = class_id;
    }

    public String getClass_name() {
        return class_name;
    }

    public void setClass_name(String class_name) {
        this.class_name = class_name;
    }

    public String getClass_description() {
        return class_description;
    }

    public void setClass_description(String class_description) {
        this.class_description = class_description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
