package com.android.activelife.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INSTRUCTOR_DATA".
 */
@Entity
public class InstructorData {

    @Id(autoincrement = true)
    private Long id;
    private String instructor_id;
    private String instructor_name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public InstructorData() {
    }

    public InstructorData(Long id) {
        this.id = id;
    }

    @Generated
    public InstructorData(Long id, String instructor_id, String instructor_name) {
        this.id = id;
        this.instructor_id = instructor_id;
        this.instructor_name = instructor_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getInstructor_id() {
        return instructor_id;
    }

    public void setInstructor_id(String instructor_id) {
        this.instructor_id = instructor_id;
    }

    public String getInstructor_name() {
        return instructor_name;
    }

    public void setInstructor_name(String instructor_name) {
        this.instructor_name = instructor_name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
