package com.android.activelife.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MESSAGES_DATA".
 */
@Entity
public class MessagesData {

    @Id(autoincrement = true)
    private Long id;
    private String message_id;
    private String message_title;
    private String message_msg;
    private String message_send_at;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MessagesData() {
    }

    public MessagesData(Long id) {
        this.id = id;
    }

    @Generated
    public MessagesData(Long id, String message_id, String message_title, String message_msg, String message_send_at) {
        this.id = id;
        this.message_id = message_id;
        this.message_title = message_title;
        this.message_msg = message_msg;
        this.message_send_at = message_send_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage_id() {
        return message_id;
    }

    public void setMessage_id(String message_id) {
        this.message_id = message_id;
    }

    public String getMessage_title() {
        return message_title;
    }

    public void setMessage_title(String message_title) {
        this.message_title = message_title;
    }

    public String getMessage_msg() {
        return message_msg;
    }

    public void setMessage_msg(String message_msg) {
        this.message_msg = message_msg;
    }

    public String getMessage_send_at() {
        return message_send_at;
    }

    public void setMessage_send_at(String message_send_at) {
        this.message_send_at = message_send_at;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
