package com.android.activelife.tampa.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.activelife.tampa.db.ScheduleDateData;

import com.android.activelife.tampa.db.ScheduleDateDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scheduleDateDataDaoConfig;

    private final ScheduleDateDataDao scheduleDateDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scheduleDateDataDaoConfig = daoConfigMap.get(ScheduleDateDataDao.class).clone();
        scheduleDateDataDaoConfig.initIdentityScope(type);

        scheduleDateDataDao = new ScheduleDateDataDao(scheduleDateDataDaoConfig, this);

        registerDao(ScheduleDateData.class, scheduleDateDataDao);
    }
    
    public void clear() {
        scheduleDateDataDaoConfig.clearIdentityScope();
    }

    public ScheduleDateDataDao getScheduleDateDataDao() {
        return scheduleDateDataDao;
    }

}
