package com.android.activelife.tampa.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DEFAULT_LOCATION_DATA".
 */
@Entity
public class DefaultLocationData {

    @Id(autoincrement = true)
    private Long id;
    private Integer postion;
    private String location_id;
    private String location_name;
    private String location_address;
    private String location_city;
    private String location_state;
    private String location_zip;
    private String location_phone;
    private String location_email;
    private String location_program_link;
    private String location_donate_link;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DefaultLocationData() {
    }

    public DefaultLocationData(Long id) {
        this.id = id;
    }

    @Generated
    public DefaultLocationData(Long id, Integer postion, String location_id, String location_name, String location_address, String location_city, String location_state, String location_zip, String location_phone, String location_email, String location_program_link, String location_donate_link) {
        this.id = id;
        this.postion = postion;
        this.location_id = location_id;
        this.location_name = location_name;
        this.location_address = location_address;
        this.location_city = location_city;
        this.location_state = location_state;
        this.location_zip = location_zip;
        this.location_phone = location_phone;
        this.location_email = location_email;
        this.location_program_link = location_program_link;
        this.location_donate_link = location_donate_link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPostion() {
        return postion;
    }

    public void setPostion(Integer postion) {
        this.postion = postion;
    }

    public String getLocation_id() {
        return location_id;
    }

    public void setLocation_id(String location_id) {
        this.location_id = location_id;
    }

    public String getLocation_name() {
        return location_name;
    }

    public void setLocation_name(String location_name) {
        this.location_name = location_name;
    }

    public String getLocation_address() {
        return location_address;
    }

    public void setLocation_address(String location_address) {
        this.location_address = location_address;
    }

    public String getLocation_city() {
        return location_city;
    }

    public void setLocation_city(String location_city) {
        this.location_city = location_city;
    }

    public String getLocation_state() {
        return location_state;
    }

    public void setLocation_state(String location_state) {
        this.location_state = location_state;
    }

    public String getLocation_zip() {
        return location_zip;
    }

    public void setLocation_zip(String location_zip) {
        this.location_zip = location_zip;
    }

    public String getLocation_phone() {
        return location_phone;
    }

    public void setLocation_phone(String location_phone) {
        this.location_phone = location_phone;
    }

    public String getLocation_email() {
        return location_email;
    }

    public void setLocation_email(String location_email) {
        this.location_email = location_email;
    }

    public String getLocation_program_link() {
        return location_program_link;
    }

    public void setLocation_program_link(String location_program_link) {
        this.location_program_link = location_program_link;
    }

    public String getLocation_donate_link() {
        return location_donate_link;
    }

    public void setLocation_donate_link(String location_donate_link) {
        this.location_donate_link = location_donate_link;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
