package com.android.activelife.tampa.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HOURS_DATA".
 */
@Entity
public class HoursData {

    @Id(autoincrement = true)
    private Long id;
    private String hours_name;
    private String hour_monday_start_time;
    private String hour_monday_end_time;
    private String hour_tuesday_start_time;
    private String hour_tuesday_end_time;
    private String hour_wednesday_start_time;
    private String hour_wednesday_end_time;
    private String hour_thursday_start_time;
    private String hour_thursday_end_time;
    private String hour_friday_start_time;
    private String hour_friday_end_time;
    private String hour_saturday_start_time;
    private String hour_saturday_end_time;
    private String hour_sunday_start_time;
    private String hour_sunday_end_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public HoursData() {
    }

    public HoursData(Long id) {
        this.id = id;
    }

    @Generated
    public HoursData(Long id, String hours_name, String hour_monday_start_time, String hour_monday_end_time, String hour_tuesday_start_time, String hour_tuesday_end_time, String hour_wednesday_start_time, String hour_wednesday_end_time, String hour_thursday_start_time, String hour_thursday_end_time, String hour_friday_start_time, String hour_friday_end_time, String hour_saturday_start_time, String hour_saturday_end_time, String hour_sunday_start_time, String hour_sunday_end_time) {
        this.id = id;
        this.hours_name = hours_name;
        this.hour_monday_start_time = hour_monday_start_time;
        this.hour_monday_end_time = hour_monday_end_time;
        this.hour_tuesday_start_time = hour_tuesday_start_time;
        this.hour_tuesday_end_time = hour_tuesday_end_time;
        this.hour_wednesday_start_time = hour_wednesday_start_time;
        this.hour_wednesday_end_time = hour_wednesday_end_time;
        this.hour_thursday_start_time = hour_thursday_start_time;
        this.hour_thursday_end_time = hour_thursday_end_time;
        this.hour_friday_start_time = hour_friday_start_time;
        this.hour_friday_end_time = hour_friday_end_time;
        this.hour_saturday_start_time = hour_saturday_start_time;
        this.hour_saturday_end_time = hour_saturday_end_time;
        this.hour_sunday_start_time = hour_sunday_start_time;
        this.hour_sunday_end_time = hour_sunday_end_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHours_name() {
        return hours_name;
    }

    public void setHours_name(String hours_name) {
        this.hours_name = hours_name;
    }

    public String getHour_monday_start_time() {
        return hour_monday_start_time;
    }

    public void setHour_monday_start_time(String hour_monday_start_time) {
        this.hour_monday_start_time = hour_monday_start_time;
    }

    public String getHour_monday_end_time() {
        return hour_monday_end_time;
    }

    public void setHour_monday_end_time(String hour_monday_end_time) {
        this.hour_monday_end_time = hour_monday_end_time;
    }

    public String getHour_tuesday_start_time() {
        return hour_tuesday_start_time;
    }

    public void setHour_tuesday_start_time(String hour_tuesday_start_time) {
        this.hour_tuesday_start_time = hour_tuesday_start_time;
    }

    public String getHour_tuesday_end_time() {
        return hour_tuesday_end_time;
    }

    public void setHour_tuesday_end_time(String hour_tuesday_end_time) {
        this.hour_tuesday_end_time = hour_tuesday_end_time;
    }

    public String getHour_wednesday_start_time() {
        return hour_wednesday_start_time;
    }

    public void setHour_wednesday_start_time(String hour_wednesday_start_time) {
        this.hour_wednesday_start_time = hour_wednesday_start_time;
    }

    public String getHour_wednesday_end_time() {
        return hour_wednesday_end_time;
    }

    public void setHour_wednesday_end_time(String hour_wednesday_end_time) {
        this.hour_wednesday_end_time = hour_wednesday_end_time;
    }

    public String getHour_thursday_start_time() {
        return hour_thursday_start_time;
    }

    public void setHour_thursday_start_time(String hour_thursday_start_time) {
        this.hour_thursday_start_time = hour_thursday_start_time;
    }

    public String getHour_thursday_end_time() {
        return hour_thursday_end_time;
    }

    public void setHour_thursday_end_time(String hour_thursday_end_time) {
        this.hour_thursday_end_time = hour_thursday_end_time;
    }

    public String getHour_friday_start_time() {
        return hour_friday_start_time;
    }

    public void setHour_friday_start_time(String hour_friday_start_time) {
        this.hour_friday_start_time = hour_friday_start_time;
    }

    public String getHour_friday_end_time() {
        return hour_friday_end_time;
    }

    public void setHour_friday_end_time(String hour_friday_end_time) {
        this.hour_friday_end_time = hour_friday_end_time;
    }

    public String getHour_saturday_start_time() {
        return hour_saturday_start_time;
    }

    public void setHour_saturday_start_time(String hour_saturday_start_time) {
        this.hour_saturday_start_time = hour_saturday_start_time;
    }

    public String getHour_saturday_end_time() {
        return hour_saturday_end_time;
    }

    public void setHour_saturday_end_time(String hour_saturday_end_time) {
        this.hour_saturday_end_time = hour_saturday_end_time;
    }

    public String getHour_sunday_start_time() {
        return hour_sunday_start_time;
    }

    public void setHour_sunday_start_time(String hour_sunday_start_time) {
        this.hour_sunday_start_time = hour_sunday_start_time;
    }

    public String getHour_sunday_end_time() {
        return hour_sunday_end_time;
    }

    public void setHour_sunday_end_time(String hour_sunday_end_time) {
        this.hour_sunday_end_time = hour_sunday_end_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
