package com.android.activelife.tampa.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEMBER_DATA".
 */
@Entity
public class MemberData {

    @Id
    private String member_id;
    private String member_name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MemberData() {
    }

    public MemberData(String member_id) {
        this.member_id = member_id;
    }

    @Generated
    public MemberData(String member_id, String member_name) {
        this.member_id = member_id;
        this.member_name = member_name;
    }

    public String getMember_id() {
        return member_id;
    }

    public void setMember_id(String member_id) {
        this.member_id = member_id;
    }

    public String getMember_name() {
        return member_name;
    }

    public void setMember_name(String member_name) {
        this.member_name = member_name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
