package com.android.activelife.tampa.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MESSAGE_LOCATION_DATA".
 */
@Entity
public class MessageLocationData {

    @Id(autoincrement = true)
    private Long id;
    private String message_id;
    private String message_title;
    private String message_msg;
    private String message_send_at;
    private String location_id;
    private String location_name;
    private String location_address;
    private String location_city;
    private String location_state;
    private String location_zip;
    private String location_phone;
    private String location_email;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MessageLocationData() {
    }

    public MessageLocationData(Long id) {
        this.id = id;
    }

    @Generated
    public MessageLocationData(Long id, String message_id, String message_title, String message_msg, String message_send_at, String location_id, String location_name, String location_address, String location_city, String location_state, String location_zip, String location_phone, String location_email) {
        this.id = id;
        this.message_id = message_id;
        this.message_title = message_title;
        this.message_msg = message_msg;
        this.message_send_at = message_send_at;
        this.location_id = location_id;
        this.location_name = location_name;
        this.location_address = location_address;
        this.location_city = location_city;
        this.location_state = location_state;
        this.location_zip = location_zip;
        this.location_phone = location_phone;
        this.location_email = location_email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage_id() {
        return message_id;
    }

    public void setMessage_id(String message_id) {
        this.message_id = message_id;
    }

    public String getMessage_title() {
        return message_title;
    }

    public void setMessage_title(String message_title) {
        this.message_title = message_title;
    }

    public String getMessage_msg() {
        return message_msg;
    }

    public void setMessage_msg(String message_msg) {
        this.message_msg = message_msg;
    }

    public String getMessage_send_at() {
        return message_send_at;
    }

    public void setMessage_send_at(String message_send_at) {
        this.message_send_at = message_send_at;
    }

    public String getLocation_id() {
        return location_id;
    }

    public void setLocation_id(String location_id) {
        this.location_id = location_id;
    }

    public String getLocation_name() {
        return location_name;
    }

    public void setLocation_name(String location_name) {
        this.location_name = location_name;
    }

    public String getLocation_address() {
        return location_address;
    }

    public void setLocation_address(String location_address) {
        this.location_address = location_address;
    }

    public String getLocation_city() {
        return location_city;
    }

    public void setLocation_city(String location_city) {
        this.location_city = location_city;
    }

    public String getLocation_state() {
        return location_state;
    }

    public void setLocation_state(String location_state) {
        this.location_state = location_state;
    }

    public String getLocation_zip() {
        return location_zip;
    }

    public void setLocation_zip(String location_zip) {
        this.location_zip = location_zip;
    }

    public String getLocation_phone() {
        return location_phone;
    }

    public void setLocation_phone(String location_phone) {
        this.location_phone = location_phone;
    }

    public String getLocation_email() {
        return location_email;
    }

    public void setLocation_email(String location_email) {
        this.location_email = location_email;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
