package com.android.activelife.tampa.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SCHEDULE_DATA".
 */
@Entity
public class ScheduleData {

    @Id(autoincrement = true)
    private Long id;
    private String schedule_type_id;
    private String schedule_type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ScheduleData() {
    }

    public ScheduleData(Long id) {
        this.id = id;
    }

    @Generated
    public ScheduleData(Long id, String schedule_type_id, String schedule_type) {
        this.id = id;
        this.schedule_type_id = schedule_type_id;
        this.schedule_type = schedule_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSchedule_type_id() {
        return schedule_type_id;
    }

    public void setSchedule_type_id(String schedule_type_id) {
        this.schedule_type_id = schedule_type_id;
    }

    public String getSchedule_type() {
        return schedule_type;
    }

    public void setSchedule_type(String schedule_type) {
        this.schedule_type = schedule_type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
