package com.android.activelife.tampa.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHEDULE_DATA".
*/
public class ScheduleDataDao extends AbstractDao<ScheduleData, Long> {

    public static final String TABLENAME = "SCHEDULE_DATA";

    /**
     * Properties of entity ScheduleData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Schedule_type_id = new Property(1, String.class, "schedule_type_id", false, "SCHEDULE_TYPE_ID");
        public final static Property Schedule_type = new Property(2, String.class, "schedule_type", false, "SCHEDULE_TYPE");
    }


    public ScheduleDataDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHEDULE_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SCHEDULE_TYPE_ID\" TEXT," + // 1: schedule_type_id
                "\"SCHEDULE_TYPE\" TEXT);"); // 2: schedule_type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHEDULE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScheduleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String schedule_type_id = entity.getSchedule_type_id();
        if (schedule_type_id != null) {
            stmt.bindString(2, schedule_type_id);
        }
 
        String schedule_type = entity.getSchedule_type();
        if (schedule_type != null) {
            stmt.bindString(3, schedule_type);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScheduleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String schedule_type_id = entity.getSchedule_type_id();
        if (schedule_type_id != null) {
            stmt.bindString(2, schedule_type_id);
        }
 
        String schedule_type = entity.getSchedule_type();
        if (schedule_type != null) {
            stmt.bindString(3, schedule_type);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ScheduleData readEntity(Cursor cursor, int offset) {
        ScheduleData entity = new ScheduleData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // schedule_type_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // schedule_type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScheduleData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSchedule_type_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSchedule_type(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ScheduleData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ScheduleData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ScheduleData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
